### ISSUE TITLE
ttnmapper.org not reachable

### ISSUE THREAD

**Issue by cprezzi** [ttnmapper/ttnmapper-website#2]
The TTN Mapper Website is not reachable at the moment. I get a "redirection error".

**Comment by jpmeijers** [comment]
Thanks for reporting. There was a configuration issue with Cloudflare. It should come right as soon as the DNS entry updates propagate out.

**Comment by cprezzi** [comment]
The Webpage is working again, but only Gateways and NO Heatmaps are shown.

**Comment by jpmeijers** [comment]
Indeed. I changed a few more settings on Cloudflare, and I think all is now working as expected. Let me know if it doesn't look right in the next hour.
