### ISSUE TITLE
TTNMapper not displaying tracks/data - moment-timezone dependency problem ?

### ISSUE THREAD

**Issue by paularthur** [ttnmapper/ttnmapper-website#4]
Update - This is the same issue as my colleague logged in #3 (which wasnt there when i started typing this...) Thanks

Hi, apols in advance if this is the wrong place.
We're having troubles with https://ttnmapper.org/devices/?device=unlessnz-mapper-005&gateways=on&lines=on&points=on
The map draws - but no tracker lines turn up. Sometimes on other browsers they do - so the data is generated and in the website/db
The web-browser error is as follows - 
![image](https://github.com/ttnmapper/ttnmapper-website/assets/12781997/783ebbfa-a767-4091-b35b-617b689f5323)
which looks like a dependency problem with https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.34/moment-timezone-with-data.min.js - that particular version 0.5.34 has issues with my browser (and a few colleagues also) - other versions seem good.
https://cdnjs.com/libraries/moment-timezone/0.5.34
https://github.com/ttnmapper/ttnmapper-website/blob/master/foot.php

Any help appreciated - and enjoying TTNMAPPER !

**Comment by jpmeijers** [comment]
Thanks for reporting this. I wasn't able to reproduce this in my browser. But when I updated the library version in my IDE it did confirm the 404 there. Both moment js libraries are now updated on both TTN Mapper and Coveragemap.net, so this problem should be solved.

**Comment by predatorfreefranklin** [comment]
Legend !!! Thanks for all the hard work JP !!

**Comment by paularthur** [comment]
Many thanks jp - it fired into life, which is good news because its such a useful tool

i checked - cloudflare still has the 404 on the old library, but thats no longer an issue for us - i'll up date their issue to say we're up and running with the newer library. Thanks again.
