### ISSUE TITLE
Stamen tiles no longer load

### ISSUE THREAD

**Issue by donnacha** [ttnmapper/ttnmapper-website#5]
As of 31 October Stamen tiles no longer load (and are set as default tiles) - recommend removing the option and setting OSM Mapnik Grayscale as default.

**Comment by jpmeijers** [comment]
Thanks for reporting this. We have changed to using the standard Openstreetmap Mapnik tiles in greyscale, and removed the Stamen Toner Lite - as Stamen would cost us $80 extra per month.
